services:
  hopledger-backend:
    image: ghcr.io/thereallinusrg/hopledger-backend:latest
    container_name: hopledger-backend
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    environment:
      - DATABASE_URL=postgresql://hopledger:${DB_PASSWORD}@hopledger-backend-db:5432/hopledger?schema=public
      - PORT=3000
      - API_KEY=${API_KEY}
      - SHOW_LOCATIONS=${SHOW_LOCATIONS:-true}
    depends_on:
      hopledger-backend-db:
        condition: service_healthy
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.hopledger-backend-web-redirect.redirectscheme.scheme: https
      traefik.http.services.hopledger-backend.loadbalancer.server.port: 3000
      traefik.http.routers.hopledger-backend-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.hopledger-backend-insecure.entrypoints: web
      traefik.http.routers.hopledger-backend-insecure.service: hopledger-backend
      traefik.http.routers.hopledger-backend-insecure.middlewares: hopledger-backend-web-redirect
      traefik.http.routers.hopledger-backend.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.hopledger-backend.entrypoints: websecure
      traefik.http.routers.hopledger-backend.service: hopledger-backend
      traefik.http.routers.hopledger-backend.tls.certresolver: myresolver
      traefik.http.routers.hopledger-backend-local-insecure.rule: Host(`hopledger-backend.${LOCAL_DOMAIN}`)
      traefik.http.routers.hopledger-backend-local-insecure.entrypoints: web
      traefik.http.routers.hopledger-backend-local-insecure.service: hopledger-backend
      traefik.http.routers.hopledger-backend-local-insecure.middlewares: hopledger-backend-web-redirect
      traefik.http.routers.hopledger-backend-local.rule: Host(`hopledger-backend.${LOCAL_DOMAIN}`)
      traefik.http.routers.hopledger-backend-local.entrypoints: websecure
      traefik.http.routers.hopledger-backend-local.service: hopledger-backend
      traefik.http.routers.hopledger-backend-local.tls: true
      runtipi.managed: true

  hopledger-backend-db:
    image: postgres:16-alpine
    container_name: hopledger-backend-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hopledger
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=hopledger
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hopledger -d hopledger"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - tipi_main_network

networks:
  tipi_main_network:
    external: true
